### ISSUE TITLE
Allow disabling name hashes on the chart level

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s-core#1037]
Currently the hash of the construct path is always suffixed to the autogenerated resource name. We should add an option on the chart to opt-out of this. 

For example, the following code:

```ts
import { App, Chart } from 'cdk8s';
import * as kplus from 'cdk8s-plus-25';

const app = new App();
const chart = new MyChart(app, 'my-chart');

new kplus.Deployment(chart, 'Deployment', {
  containers: [{ image: 'nginx' }]
});

app.synth();
```

Will generate a `Deployment` resource with the following name: `my-chart-deployment-c8c354dd`. 

> See https://docs.aws.amazon.com/cdk/v2/guide/identifiers.html#identifiers_unique_ids for reasoning why we add the hash.

In some cases the hash is undesirable and currently users are forced to override the `Chart.generateObjectName` method to drop the hashes. Lets make this easier by adding a chart property that allows dropping the hashes.

> See https://github.com/cdk8s-team/cdk8s/issues/232

**Comment by sumupitchayan** [comment]
Created a [PR](https://github.com/cdk8s-team/cdk8s-core/pull/1079) - can close this issue once it's reviewed and merged!

**Comment by sumupitchayan** [comment]
Looks like this issue overlaps with this one https://github.com/cdk8s-team/cdk8s/issues/232
