### ISSUE TITLE
Remove backport from optionalDependencies

### ISSUE THREAD

**Issue by shinebayar-g** [cdk8s-team/cdk8s-core#2049]
### Description of the bug:

Package called `backport` is defined in the `optionalDependencies`. If I'm understanding correctly packages defined in `optionalDependencies` is installed by default. Thus considered as a direct dependency and its dependencies are getting flagged in security vulnerability. (Like `axios` for example).

https://github.com/cdk8s-team/cdk8s-core/blob/bc6f48300790eab2f2833fe5b0a1f5e6ea813e28/package.json#L174-L176

This is confirmed in npm as well.
![image](https://github.com/cdk8s-team/cdk8s-core/assets/3091558/d72b835a-0d51-4af3-8862-964c879b0659)
---
![image](https://github.com/cdk8s-team/cdk8s-core/assets/3091558/209f48f3-c1b9-4fcf-9f99-eae410717d9e)

I suggest we should move this to `devDependencies`.

### Environment:

  - **Framework Version**:
  - **OS**:

### Other:

---

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Oh nice. We we should move it to `devDependencies` for sure. It used to be there, but it required a node version bump in all our workflows (because `backport` has higher node requirements than cdk8s) - but this makes it worth it. 

Thanks!
