### ISSUE TITLE
Deleting objects (pruning)

### ISSUE THREAD

**Issue by eladb** [cdk8s-team/cdk8s-core#33]
We propose that cdk8s will have built-in support for [`kubectl --prune`](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-to-delete-objects).

Consider the [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

**Comment by Chriscbr** [comment]
Keep
