### ISSUE TITLE
Should `app.kubernetes.io/managed-by: Helm` be removed for Helm charts output?

### ISSUE THREAD

**Issue by akefirad** [cdk8s-team/cdk8s-core#478]
I'm not deeply familiar how Helm works and not sure if it's really needed. But it seems to me that having the fabled at the very least is confusing, since the app is not really managed by Helm, in my case it's managed via ArgoCD. Does that make sense to remove the label from the generated templates? Currently I'm doing it using a `JsonPatch.remove`. Any thoughts? Thanks.

**Comment by iliapolo** [comment]
Converted to discussion: https://github.com/cdk8s-team/cdk8s-core/discussions/746
