### ISSUE TITLE
Provide namespace support for Helm

### ISSUE THREAD

**Issue by kesavkolla** [cdk8s-team/cdk8s-core#749]
There is no way to specify namespace while using Helm construct. All the objects that are part of helm rendering are coming into default namespace. It would be good to specify the namespace parameter to helm so that things will be generated with proper namespace.

**Comment by iliapolo** [comment]
Interesting. I suppose allowing any type of metadata to be applied on all resources in the chart would be useful.

I'm classifying this as a p2, which means we are not planning to address it until we see more community ask, but PR's are welcome :)

In the meantime, here is a workaround:

```ts
const helmChart = new Helm(...);
helm.apiObjects.forEach(c => ApiObject.of(c)
  .addJsonPatch(JsonPatch.add('/metadata/namespace', 'namespace')));
```

**Comment by kesavkolla** [comment]
I thought of doing that workaround but I figured out the namespace is not just the one to patch. It really depends on chart template where all the places they use namespace.

The change would be really trivial in my opinion. We just have to pass as CLI argument to helm command.

Infact all CLI flags of the helm template command should be made available to Helm construct.

**Comment by kesavkolla** [comment]
I just realized there is already **helmFlags** available to Helm construct. I can use that to pass namespace as parameter.
