### ISSUE TITLE
Include construct won't work with local files

### ISSUE THREAD

**Issue by mbonig** [cdk8s-team/cdk8s-core#88]
I've got an existing yaml resource file I'd like to include:

```
new Include(this, 'Deployment', {
  url: `../../deployment-${props.env}.yaml`,
});
```

However, I get an error about not being able to determine the protocol:

```
Error: unable to determine protocol from url: ../../deployment-staging.yaml
```

during the _loadurl.js script.

The docs indicate I can point it at a file but I'm not sure how this would every work as the url.parse() will take absolute and relative file pathing and report no protocol 

Node v14

**Comment by jasonroelofs** [comment]
For the next person who runs into this: `url` is required to be a full path, e.g.:

```
url: `${__dirname}/../../deployment-${props.env}.yaml`
```

The `Include` docs are actually wrong here as it shows using a local-relative path. Also it would be nice if the failure included a better error message.
